### PR TITLE
Directed .pt files to checkpoints.

### PR DESCRIPTION
**Pull request by samuelmaina**
@GemmaTuron ,
I  guess the output is supposed to be a one column. I have moved the .pt file
I have looked at the first commit (initial commit) and the code  reads 
```

    # Ensemble predictions
    avg_preds = sum_preds / len(args.checkpoint_paths)

    # Save predictions
    assert len(test_data) == len(avg_preds)

    # Put Nones for invalid smiles
    args.valid_indices = valid_indices
    avg_preds = np.array(avg_preds)
    test_smiles = full_data.smiles()
    return avg_preds, test_smiles
```
which is the current version of the make_prediction function in the grover.main.py file. 
Maybe you can look into it and give me direction on what to do

### CODE REVIEW

**Comment by samuelmaina** [comment]
Made the changes. Why aren't the workflows rerunning automatically when I add a commit to the PR?

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

The workflows have run, and the path is not well specified.

**Comment by GemmaTuron** [comment]
Regarding the one column output, have you tried to run the original code to be sure? The results would be different if we are looking at QM7 or QM7b - Also please comment this with your mentor

**Comment by GemmaTuron** [comment]
@samuelmaina 

Please revise the paths, the test is still failing

**Comment by samuelmaina** [comment]
@GemmaTuron ,
It is running the previous commits. It hasn't detected the new changes.I will close this  PR and open another one.

**Pull request closed without merging**
